---
title: "Recap Vaccine"
format: html
---

# Recap original model:

```{r}
source(file = "SMILE_v1.1.R")
source(file = "smile_main.R")
```


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(cowplot)
```

Test that they do the same, at least the final function 

```{r}
tau=10
b0=-30
b1=0.85
period=3*52

# Case 5.0: Low Dispersion. Mean dispersion effort is 0.1
theta=10
sim5.0		<-	smile5(b0=b0,b1=b1,period=period,tau=tau,theta=theta,years=10)
```

```{r}
sim5_1 <- smile_fx(b0 = -30, b1 = 0.85, period = 3*52, theta = 10, tau = 10, years = 10)
```

visualize the results from both:


```{r echo=FALSE, fig.width=10, fig.height=12}

# Susceptibles
sim5.0$Suceptibles %>% tibble() %>% rownames_to_column() %>% purrr::set_names(c("week", "S")) %>% mutate(fx = "OG") %>% 
  mutate(week = as.numeric(week)) -> S_comp
  
S_comp %>% 
  bind_rows(sim5_1$Suceptibles %>% tibble() %>% rownames_to_column() %>%
              purrr::set_names(c("week", "S")) %>% mutate(fx = "NEW", week = as.numeric(week))) %>% 
  ggplot(aes(x = week, y = S)) +
  facet_wrap(~fx) +
  geom_line() +
  theme_bw() -> S_plot

# Immune
sim5.0$Immune %>% tibble() %>% rownames_to_column() %>% purrr::set_names(c("week", "M")) %>% mutate(fx = "OG") %>% 
  mutate(week = as.numeric(week)) -> M_comp
  
M_comp %>% 
  bind_rows(sim5_1$Immune %>% tibble() %>% rownames_to_column() %>%
              purrr::set_names(c("week", "M")) %>% mutate(fx = "NEW", week = as.numeric(week))) %>% 
  ggplot(aes(x = week, y = M)) +
  facet_wrap(~fx) +
  geom_line() +
  theme_bw() -> M_plot

# Infected
sim5.0$Infected %>% tibble() %>% rownames_to_column() %>% purrr::set_names(c("week", "I")) %>% mutate(fx = "OG") %>% 
  mutate(week = as.numeric(week)) -> I_comp
  
I_comp %>% 
  bind_rows(sim5_1$Infected %>% tibble() %>% rownames_to_column() %>%
              purrr::set_names(c("week", "I")) %>% mutate(fx = "NEW", week = as.numeric(week))) %>% 
  ggplot(aes(x = week, y = I)) +
  facet_wrap(~fx) +
  geom_line() +
  theme_bw() -> I_plot

# LIZ
sim5.0$LIZ %>% tibble() %>% rownames_to_column() %>% purrr::set_names(c("week", "L")) %>% mutate(fx = "OG") %>% 
  mutate(week = as.numeric(week)) -> L_comp
  
L_comp %>% 
  bind_rows(sim5_1$LIZ %>% tibble() %>% rownames_to_column() %>%
              purrr::set_names(c("week", "L")) %>% mutate(fx = "NEW", week = as.numeric(week))) %>% 
  ggplot(aes(x = week, y = L)) +
  facet_wrap(~fx) +
  geom_line() +
  theme_bw() -> L_plot


# E
sim5.0$E %>% tibble() %>% rownames_to_column() %>% purrr::set_names(c("week", "E")) %>% mutate(fx = "OG") %>% 
  mutate(week = as.numeric(week)) -> E_comp
  
E_comp %>% 
  bind_rows(sim5_1$E %>% tibble() %>% rownames_to_column() %>%
              purrr::set_names(c("week", "E")) %>% mutate(fx = "NEW", week = as.numeric(week))) %>% 
  ggplot(aes(x = week, y = E)) +
  facet_wrap(~fx) +
  geom_line() +
  theme_bw() -> E_plot

plot_grid(S_plot, M_plot, I_plot, L_plot, E_plot, ncol = 1)

```

